name: Lint

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn build
      - uses: jonaszjestem/eslint-action@test
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
