name: Lint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jonaszjestem/eslint-action@test
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
